ESTADOS = {
    0 : 'EXTERIOR', 1 : 'AC', 2 : 'AL', 3 : 'AP', 4 : 'AM', 5 : 'BA', 6 : 'CE', 7 : 'DF', 8 : 'ES', 9 : 'GO', 10 : 'MA', 11 : 'MT', 12 : 'MS', 13 : 'MG', 14 : 'PA', 15 : 'PB', 16 : 'PR', 17 : 'PE', 18 : 'PI', 19 : 'RJ', 20 : 'RN', 21 : 'RS', 22 : 'RO', 23 : 'RR', 24 : 'SC', 25 : 'SP', 26 : 'SE', 27 : 'TO',
}

CONTAS = {
    0 : 'DESCONHECIDO', 1 : 'ASUS', 2 : 'CANON', 3 : 'COMPAL', 4 : 'CTD', 5 : 'DATALAB', 6 : 'DESIGN', 7 : 'DEVOPS', 8 : 'FTI', 9 : 'HONDA', 10 : 'IGENICO', 11 : 'LL', 12 : 'S2', 13 : 'TREINAMENTO', 14 : 'WESTROCK',
}

CURSOS = {
    0 : 'DESCONHECIDO', 1 : 'ANALISE E DESENVOLVIMENTO DE SIG_SETMAS', 2 : 'CIENCIA DA COMPUTACAO', 3 : 'CIENCIA DE DADOS', 4 : 'CIENCIA DE DADOS E INTELIGENCIA ARTIFICIAL', 5 : 'ENGENHARIA DA COMPUTAÇÃO', 6 : 'ENGENHARIA DE CONTROLE E AUTOMACAO', 7 : 'ENGENHARIA DE PRODUCAO', 8 : 'ENGENHARIA MECATRONICA', 9 : 'ENSINO MEDIO + TECNICO EM INFORMATICA', 10 : 'GRADUACAO EM TECNOLOGIA E MARKETING', 11 : 'SISTEMA PARA INTERNET', 12 : 'TECNICO EM DESENVOLVIMENTO DE SISTEMAS', 13 : 'TECNOLOGIA DA IFORMACAO', 14 : 'TECNOLOGIA EM ANALISE DE DESENVOLVIMENTO DE SISTEMAS', 15 : 'TELEMATICA',
}

LINGUAGENS = {
    0 : 'VHDL', 1 : 'ASSEMBLY', 2 : 'C', 3 : 'C++', 4 : 'C#', 5 : 'JAVA', 6 : 'JS', 7 : 'PYTHON', 8 : 'PERL', 9 : 'PHP', 10 : 'RUBY', 11 : 'GO', 12 : 'SWIFT', 13 : 'VB', 14 : 'RUBYMATLAB',
}