ESTADOS = {
        'AC' : 1, 'AL' : 2, 'AP' : 3, 'AM' : 4, 'BA' : 5, 'CE' : 6, 'DF' : 7, 'ES' : 8, 'GO' : 9, 'MA' : 10, 'MT' : 11, 'MS' : 12, 'MG' : 13, 'PA' : 14, 'PB' : 15, 'PR' : 16, 'PE' : 17, 'PI' : 18, 'RJ' : 19, 'RN' : 20, 'RS' : 21, 'RO' : 22, 'RR' : 23, 'SC' : 24, 'SP' : 25, 'SE' : 26, 'TO' : 27, 
    }

CONTAS = {
    'DESCONHECIDO': 0, 'ASUS': 1, 'CANON': 2, 'COMPAL': 3, 'CTD': 4, 'DATALAB': 5, 'DESIGN': 6, 'DEVOPS': 7, 'FTI': 8, 'HONDA': 9, 'IGENICO': 10, 'LL': 11, 'S2': 12, 'TREINAMENTO': 13, 'WESTROCK': 14,
}

CURSOS = {
    'DESCONHECIDO' : 0, 'ANALISE E DESENVOLVIMENTO DE SIG_SETMAS' : 1, 'CIENCIA DA COMPUTACAO' : 2, 'CIENCIA DE DADOS' : 3, 'CIENCIA DE DADOS E INTELIGENCIA ARTIFICIAL' : 4, 'ENGENHARIA DA COMPUTAÇÃO' : 5, 'ENGENHARIA DE CONTROLE E AUTOMACAO' : 6, 'ENGENHARIA DE PRODUCAO' : 7, 'ENGENHARIA MECATRONICA' : 8, 'ENSINO MEDIO + TECNICO EM INFORMATICA' : 9, 'GRADUACAO EM TECNOLOGIA E MARKETING' : 10, 'SISTEMA PARA INTERNET' : 11, 'TECNICO EM DESENVOLVIMENTO DE SISTEMAS' : 12, 'TECNOLOGIA DA IFORMACAO' : 13, 'TECNOLOGIA EM ANALISE DE DESENVOLVIMENTO DE SISTEMAS' : 14, 'TELEMATICA' : 15
}

LINGUAGENS = {
    'VHDL' : 0, 'ASSEMBLY' : 1, 'C' : 2, 'C++' : 3, 'C#' : 4, 'JAVA' : 5, 'JS' : 6, 'PYTHON' : 7, 'PERL' : 8, 'PHP' : 9, 'RUBY' : 10, 'GO' : 11, 'SWIFT' : 12, 'VB' : 13, 'RUBYMATLAB' : 14
}